### ISSUE TITLE
Bienvenue sur le projet

### ISSUE THREAD

**Issue by lokkotara** [devs-coffee/frontend-collab-chat-project#1]
Voici la toute première pierre de notre projet. 

Il me paraissait important de vous accueillir comme il se doit et cela n'a absolument rien à voir avec ma frustration de ne jamais avoir pu utiliser le label **"good first issue"** auparavant ;)

Pour clore cette issue, je vous propose de laisser chacun un commentaire sous cette issue ;)

**Comment by WhitedogWarren** [comment]
Clap, clap :)
