### ISSUE TITLE
Quel state manager choisir entre context API et Redux ?

### ISSUE THREAD

**Issue by lokkotara** [devs-coffee/frontend-collab-chat-project#3]
Pour notre projet, l'utilisation d'un gestionnaire de state globale nous paraît évident pour une facilité de compréhension et une meilleure maintenabilité. Il existe un tas de solutions disponibles, mais nous avons décidé de nous focaliser sur 2 choix en particulier : Redux et Context API. Voici ci-dessous un comparatif entre ces deux librairies pour nous aider à prendre une décision :

![Capture d’écran 2022-09-03 163753](https://user-images.githubusercontent.com/9353050/188275638-310a13c2-66c4-4dc7-99d8-6e9de3d5e830.png)

Donc pour conclure de ce que j'ai pu lire à gauche et à droite sur le web, Redux brillera plus sur de moyennes et grosses applis, avec un state conséquent et/ou complexe qui demande une mise à jour fréquente de ses datas. Il sera par contre overkill et plus contraignant à mettre en place sur de petites applis qui partage de la data fixe ou peu changeante. Là où Contexct API sera parfait.

Voici 2 / 3 liens sur ce sujet : 

- https://dev.to/ruppysuppy/redux-vs-context-api-when-to-use-them-4k3p
- https://www.upbeatcode.com/react/when-to-use-context-api-vs-redux/
- https://www.ibrahima-ndaw.com/fr/blog/redux-vs-react-context-which-one-should-you-choose/

**Comment by WhitedogWarren** [comment]
Je réitère mon vote en faveur de context API.
En effet, je ne pense pas que l'on ait besoin d'énormément de contextes différents.
Disons un auth, un pour socket.io ( et encore il peut très bien être collé dans auth ), et quoi d'autre ?
La mutation des datas, il y a bien les messages, mais est-ce que ça mute "beaucoup" ? Et de toute façon, a-t-on besoin d'un contexte pour les messages ?

**Comment by lokkotara** [comment]
J'en profite pour fermer cette issue puisque notre choix a été fait en faveur de redux toolkit qui offre une gestion de state globale complète et robuste. Redux toolkit simplifie la mise en place du store, et permet une meilleure lisibilité
