### ISSUE TITLE
Affichage de l'image d'avatar

### ISSUE THREAD

**Issue by lokkotara** [devs-coffee/frontend-collab-chat-project#30]
Le 04/06/2023, Je me suis connecté et j'ai publié plusieurs messages sur différents serveurs. A chaque fois, l'image d'avatar à côté de mon pseudo s'affiche correctement. Par contre, si je me déconnecte de l'appli et que je me reconnecte, toutes les les images d'avatar ont disparues.

**Comment by WhitedogWarren** [comment]
À dire vrai, c'est plutôt bizarre que tu aies eu les avatars la première fois ^^
J'ai déjà créé une branche pour ça, je passe la tâche à "en cours"

**Comment by lokkotara** [comment]
Pour préciser. Tous les messages que je poste durant une session (entre connexion et déconnexion) vont afficher mon avatar à côté. lorsque je me déco /reco, là j'ai perdu toutes les photos.

**Comment by WhitedogWarren** [comment]
Ah si, j'ai pigé.
Tu as ton avatar dans le state quand tu poste les messages. Donc il s'affiche.
Par contre, quand tu récupère les messages postés avant ta connexion, il manque juste la partie qui s'occupe d'aller fetch les images d'avatar. J'ai une branche pour ça. Bon, actuellement je me suis encore mélangé les crayons avec git, donc je peux pas push, j'ai plein d'erreurs.
Mais je suis sur le coup.

**Comment by WhitedogWarren** [comment]
Bon, j'ai fait une PR pour ma branche feature-users-slice.
À mon humble avis il faudrait merger, tester et éventuellement faire un hotfix ou deux sur dev ( j'ai eu pas mal de conflits à résoudre, on est pas à l'abri d'une embrouille ).
Mais si tout se passe bien les avatars seront désormais affichés dans la liste des messages de channels.

**Comment by WhitedogWarren** [comment]
Il faudra donc un hotfix, les users sont bien dans le slice, mais les avatars n'apparaissent pas dans la liste des messages.
