### ISSUE TITLE
Souci avec l'ajout de serveur

### ISSUE THREAD

**Issue by lokkotara** [devs-coffee/frontend-collab-chat-project#31]
Le 04/06/2023 : J'ai remarqué un comportement bizarre lors de ma navigation. 

Je suis connecté et je suis sur la page dashboard. 
Si je clique sur la loupe, un champ de recherche s'ouvre, 
si je clique sur envoyer sans rien remplir, j'ai la liste de tous les serveurs. 
Si de là, je clique sur un serveur que je n'ai pas créé, je peux consulter et écrire des messages sur ce serveur sans forcément être ajouter à la liste ("join").
 Si je reviens sur dashboard, ce serveur apparaît dans ma liste de serveur (temporairement jusqu'à déconnexion). 
Si je retourne ensuite sur ce serveur et que j'appuie maintenant sur "join", il apparaît maintenant deux fois dans ma liste de serveurs sur dashboard

**Comment by WhitedogWarren** [comment]
- En ce qui concerne la duplication du serveur lors du join, j'ai la solution
Dans pages / serverDisplay, à la ligne 68, il faut remplacer le dispatch(addServer()) par dispatch(updateServer()).
Ce reducer devra permettre l'ajout du server dans le slice ou la mise à jour si il est déjà présent. Le reducar addServer pourra alors être supprimé.
- pour la recherche avec une chaîne vide, c'est un petit correctif à effectuer côté back, ça ^^
- pour le fait de pouvoir poster quand on est pas membre, il y a un souci côté front ET côté back
- pour le fait qu'un server consulté apparaisse dans le DashboardServerHeading, c'est une très bonne remarque, le composant doit être remanié. Il ne faut plus afficher tous les serveurs du slice, mais seulement ceux dont on est membre.

Cela fait donc 4 tâches, à voir si on crée des tickets supplémentaires.

**Comment by WhitedogWarren** [comment]
- Duplication du serveur dans le state : done
- poster quand on est pas membre, fix côté back. => [PR](https://github.com/devs-coffee/backend-collab-chat-project/pull/36)

**Comment by julienb86** [comment]
Pr en cours sur la recherche d'un serveur avec une string vide

**Comment by WhitedogWarren** [comment]
Petit état des lieux :

`si je clique sur envoyer sans rien remplir, j'ai la liste de tous les serveurs.`
Done côté back. Petit fix à prévoir côté front, peut-être.

`Si de là, je clique sur un serveur que je n'ai pas créé, je peux consulter et écrire des messages sur ce serveur sans forcément être ajouter à la liste ("join").`
Done côté back. Petit fix à prévoir en front pour désactiver ou faire disparaître le MessageEditor.

`Si je reviens sur dashboard, ce serveur apparaît dans ma liste de serveur (temporairement jusqu'à déconnexion).`
Done on both side. On n'affiche plus que les serveurs dont le user est membre.

`Si je retourne ensuite sur ce serveur et que j'appuie maintenant sur "join", il apparaît maintenant deux fois dans ma liste de serveurs sur dashboard`
Done.

Résultat des courses, il reste une PR à merger côté front ( https://github.com/devs-coffee/frontend-collab-chat-project/pull/40 ) et deux fixs côté front à faire ( désactiver l'envoi d'un search avec chaîne vide et désactiver le MessageEditor si on est pas membre du serveur )

**Comment by WhitedogWarren** [comment]
MAJ :
Il ne reste que les deux derniers fix côté front, les PR sont faites.
