### ISSUE TITLE
Problème de connexion

### ISSUE THREAD

**Issue by lokkotara** [devs-coffee/frontend-collab-chat-project#32]
le 05/06/2023 : Hier j'ai créé un compte depuis mon mobile sur l'appli, aucun souci. Aujourd'hui, je me connecte depuis mobile, toujours aucun souci. Le problème survient lorsque j'essaye de me connecter depuis l'ordi au boulot. Lorsque je rentre les identifiants, j'ai un message en bas à gauche me disant "email et/ou mot de passe invalide". J'ai aussi des messages d'erreur en console navigateur à propos des CORS policies

![Image](https://github.com/devs-coffee/frontend-collab-chat-project/assets/9353050/e4d49501-7976-4d88-b213-dddb2c2f6ca9)

**Comment by WhitedogWarren** [comment]
Aaaah, le fameux problème CORS...
Je pense savoir ce que c'est. Tu as du te connecter sur un build, et entre temps on a fait une MAJ, et le souci que j'avais résolu est réapparu. Il s'agit simplement, dans le Fetcher, d'ajouter le header.mode : 'cors' et ça devrait le faire.

**Comment by julienb86** [comment]
Non reproduit
