### ISSUE TITLE
Options du dernier message non visibles

### ISSUE THREAD

**Issue by WhitedogWarren** [devs-coffee/frontend-collab-chat-project#33]
Dans la liste des messages d'un channel de serveur, il est impossible d'accéder aux options ( modifier ou supprimer ) du message le plus récent ( quand on en est l'auteur, bien sûr ).

**Comment by WhitedogWarren** [comment]
Après une rapide analyse, il se trouve que le bouton "options" du dernier message fonctionne.
Simplement, les options se développent sans entraîner de scroll, les options ne sont donc pas visibles, mais elles sont bien là.
Je change donc le label et le titre du ticket.

**Comment by Jerome-Marichez** [comment]
Dès les deux dernières PR merged je travaille à résoudre ce problème.

**Comment by Jerome-Marichez** [comment]
La PR: https://github.com/devs-coffee/frontend-collab-chat-project/pull/70
