### ISSUE TITLE
Merge dev dans main

### ISSUE THREAD

**Issue by julienb86** [devs-coffee/frontend-collab-chat-project#36]
Avoir le code prod sur main et non dev

**Comment by WhitedogWarren** [comment]
Oui, on pourrait faire un merge sur main, mais il y aurait encore quelques petits détails à régler pour faire une version propre.
J'y réfléchis et je propose une liste de prérequis avant le merge sur main.
Par exemple, j'avais le usersSlice en cours de rédaction, et en rouvrant la branche j'ai du faire une bourde, parce que ton messagesSlice est pas content.

**Comment by WhitedogWarren** [comment]
Bon, après avoir un peu réfléchi sur la question, je pense qu'il faudrait régler quelques petits soucis avant de merge.

Premièrement il y aurait cette issue à boucler. Il n'y a rien de bien méchant. Une fois cette issue réglée, on pourra merger le back.
https://github.com/devs-coffee/frontend-collab-chat-project/issues/31

Autres petites babioles pour le front, il y aurait le refresh sur la page auth :
https://github.com/devs-coffee/frontend-collab-chat-project/issues/35
Et peut-être jeter un coup d'oeil sur le bouton option du dernier message ( qui est inactif ) :
https://github.com/devs-coffee/frontend-collab-chat-project/issues/33

Je pense qu'avec ça on partira sur des main "sains".

**Comment by Jerome-Marichez** [comment]
un jour il faudra bien merger dans main un jour : )

**Comment by julienb86** [comment]
Yes je m en occupe dans la semaine

**Comment by Jerome-Marichez** [comment]
Un merge de dev vers main à été fait par @julienb86
