### ISSUE TITLE
Darkmode switch ne fonctionne pas comme attendu à la connexion

### ISSUE THREAD

**Issue by julienb86** [devs-coffee/frontend-collab-chat-project#61]
<img width="950" alt="image" src="https://github.com/devs-coffee/frontend-collab-chat-project/assets/32814329/6c9290f3-9a56-422b-b535-a5e2cfe7f3fa">

**Comment by Jerome-Marichez** [comment]
C'est fixe normalement sur cette PR: https://github.com/devs-coffee/frontend-collab-chat-project/pull/62
