### ISSUE TITLE
Mettre en place Rich Text Editor

### ISSUE THREAD

**Issue by WhitedogWarren** [devs-coffee/frontend-collab-chat-project#67]
Afin de donner une meilleure tête et surtout ajouter des fonctionnalités à l'input de message, il faudrait mettre en place Rich Text Editor dans le composant MessageEditor.
https://richtexteditor.com/

**Comment by Jerome-Marichez** [comment]
RichTextEditor est-il un indispensable ou il est possible d'intégrer une autre solution ? 
https://github.com/jpuri/react-draft-wysiwyg
https://jpuri.github.io/react-draft-wysiwyg/#/

M'a l'air pas trop mal il à l'avantage d'être opensource + entièrement gratuit, il est également basée sur https://draftjs.org/ 
Le composant supporte aussi les différents styles ce qui permet de l'ajuster au thème (Dark/Light Theme).

**Comment by WhitedogWarren** [comment]
Ah, ben comme tu le sens.
Le but serait d'avoir un meilleur style, déjà, et si possible des fonctionnalités classiques, comme la possibilité d'ajouter des images, des smileys, etc.

**Comment by Jerome-Marichez** [comment]
Ok superbe :) 
C'est bientôt prêt de mon côté 👍
